# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "PAT"
#   url = "/pat"
#   weight = 10

[[main]]
  name = "GO"
  url = "go"
  weight = 20

[[main]]
  name = "Python"
  url = "python"
  weight = 30

# [[main]]
#   name = "C++"
#   url = "/cpp"
#   weight = 40

[[main]]
  name = "刷题"
  url = "/code"
  weight = 60

[[main]]
  name = "Project"
  url = "/project"
  weight = 70

[[main]]
  name = "MIX"
  url = "/mix"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
